name: run TDD java JUnit 5 test
on: push
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 
        uses: actions/setup-java@v1
        with:
          java-version: 16.0.2
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m3
          key: ${{ runner.os }}-m3-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m3
      - name: Run my tests using Maven
        run: mvn -B test --file pom.xml
